### ISSUE TITLE
JNI crash when copying Records

### ISSUE THREAD

**Issue by ktarbet** [HydrologicEngineeringCenter/hec-dss#125]
To reproduce: copy a record from attached DSS  (version 6) file to another dss file(version 6). 

If destination is DSS7 there is no issue.

The error occurs on a specific data set: 
//STEVENSON/ELEV/01NOV2020/1HOUR/DCP-REV/
//STEVENSON/ELEV/01NOV2021/1HOUR/DCP-REV/

Other records with 'ELEV' copy ok, so it appears to be specific to that record?

![image](https://user-images.githubusercontent.com/4818531/181286956-8a826229-5ce9-4559-a470-44c4d0c0a654.png)
[hs_err_pid1468.log](https://github.com/HydrologicEngineeringCenter/hec-dss/files/9200499/hs_err_pid1468.log)
[forecast-src.zip](https://github.com/HydrologicEngineeringCenter/hec-dss/files/9200931/forecast-src.zip)

**Comment by ktarbet** [comment]
A NULL string (supplemental info) is being passed to Fortran causing a crash.

The method char *userHeaderToString(const int *userHeader, const int userHeaderNumber) is returning a NULL with the following integer input.

userHeader[0]=0
userHeader[1]=538997862
userHeader[2]=538976288
userHeader[3]=1414745673
userHeader[4]=1279350317
userHeader[5]=0
userHeader[6]=542395719
userHeader[7]=538976288
userHeader[8]=538976288
userHeader[9]=538976288
userHeader[10]=538976288
userHeader[11]=538976288
userHeader[12]=0
userHeader[13]=0
userHeader[14]=0
userHeader[15]=0
userHeader[16]=0
userHeader[17]=0
userHeader[18]=0
userHeader[19]=0
userHeader[20]=0
userHeader[21]=0
userHeader[22]=0
userHeader[23]=0

![image](https://user-images.githubusercontent.com/4818531/181344286-ede93c88-2af4-49ab-bb94-1efdfb2ccb0f.png)

I can prevent the crash by checking for the NULL, and using an empty string instead.

**Comment by perrymanmd** [comment]
Is userHeaderToString *returning* the null string, or is the userHeader[0] = 0 on input?

**Comment by perrymanmd** [comment]
Never mind - I see the answer in the message.
