### ISSUE TITLE
Compiled DLL Request

### ISSUE THREAD

**Issue by DJHostetler** [HydrologicEngineeringCenter/hec-dss#229]
My apologies as this is not a bug report, but I am trying to get access to the compiled version of the hec-dss library for 64-bit windows to use with the HEC-DSS python library. The USACE website currently gives an error message for the download link to the binary files. I tried compiling myself, but the Fortran compilation is running into issues. Is there a way to get the latest compiled dll?

**Comment by ktarbet** [comment]
There is a version of the dll in the hec-dss-python draft release that should work.  

https://github.com/HydrologicEngineeringCenter/hec-dss-python/releases/tag/v0.0.1-alpha

**Comment by DJHostetler** [comment]
@ktarbet Thank you!
