### ISSUE TITLE
Paired Data Label not being stored.

### ISSUE THREAD

**Issue by mjbarryfb** [HydrologicEngineeringCenter/hec-dss#232]
I was running a test using hecdss.dll in VBA and have found an issue when saving paired data.  The labels are not getting stored.  I have checked the label bytes when reading paired data and the match the bytes when writing paired data and they match.  However, the labels do not get stored to the output.  I have attached my test workbook and the dss file I was testing with.
[dss7_vba.zip](https://github.com/HydrologicEngineeringCenter/hec-dss/files/15087493/dss7_vba.zip)

**Comment by ktarbet** [comment]
@mjbarryfb  May I close this issue?

**Comment by mjbarryfb** [comment]
Yes, you may.  I tested on my end and labels are writing now.

Max Barry
D 916.679.8882

hdrinc.com/follow-us<http://hdrinc.com/follow-us>
