### ISSUE TITLE
DSS shared library  .dll/.so  API for both Java and .net consumers.

### ISSUE THREAD

**Issue by ktarbet** [HydrologicEngineeringCenter/hec-dss#41]
Thinking about #31 

Any thoughts if we should attempt to make a new dll/so   called   '[lib]dss.so /  dss.dll  '

Can that dss.so be used by both JNA and cross platform C# P/Invoke?

The new shared library would have the minimal and (nicer names) interface to DSS

![image](https://user-images.githubusercontent.com/4818531/141166465-56b9de67-6e39-4f6b-8826-fcb35e04c74f.png)

**Comment by ktarbet** [comment]
If Fortran were also supported the following are functions are in use:

| Name      | Description |
| ----------- | ----------- |
| XREAL_ |  convert character to float   |
| UPCASE_| convert character to upper case|
| DATJUL_| convert character date such as 'March 21, 1982' to days since Dec 31,1899 |
|YMDDAT_||
|GETIME_||
|JULDAT_||
|CHRLNB_||
|IDAYWK_||
|INCTIM_||
|IYMDJL_||
|JLIYMD_||
|WHEN_||
|CURTIM_||
|ZSET_||
|ZOPEN6_||
|ZOPEN_||
|ZCLOSE_||
|ZGINTL_||
|ZPATH_||
|ZCHKPN_||
|ZUFPN_||
|ZSRTS_||
|ZSRTSC_||
|ZSITS_||
|ZSITSXD_||
|M2IHM_||
|IHM2M_||
|ZPTPFD_||
|LJSTR_||
|ZSPD_||
|ZGTPFD_||
|ZDTYPE_||
|ZPTDTS_||

**Comment by MikeNeilson** [comment]
This seems like a good idea. And a good way to start constraining/simplifying what's actually built by dss itself.

**Comment by perrymanmd** [comment]
When I was building DSS v6 from a common codebase for Windows, Linux, and Solaris, I always built a heclib.dll/heclib.so just for that purpose, but it had all of the routines in heclib.lib/heclib.a available. It was never used for anything, though.
